### ISSUE TITLE
Application Management page

### ISSUE THREAD

**Issue by derrell** [app-inventor-gallery/aig#19]
This page is not working fully. Complete it.

Be sure that application flags management can be accomplished from here.

**Comment by derrell** [comment]
Assigned to Mike

**Comment by mijoda** [comment]
Description of AICG Application Management Module

This module allows administrators to deal with abusive apps by
deleting them, or by editing certain of their fields.  The main page
contains a table of apps whose columns are fields of interest to an
admin.  The table may be ordered on any of the columns; initially, it
is usefully ordered by descending number of flags.

An app can be deleted from the table, or an editor can be brought up
which permits editing of the following fields:

Title
Description
Categories and Tags
Status (active, pending, banned, etc.)
Flags

The first four fields can be edited arbitrarily.  Editing of the
status field allows an app to be banned; then the user can be
contacted to request changes or feedback.

Since flag objects are not yet fully implemented--the explanation
field is always set to "inappropriate" in the front end--the only
available action on flags is, when an app is deemed acceptable, to
press a button that removes all flags for the app and resets the flag
count to zero.  Then the status can be manually changed from "banned"
or "pending" to "active".

The image associated with an app is also visible in the cell editor for
inspection by the admin.

This initial version is not pretty, and lacks some useful features,
but will provide essential basic functionality, and is only visible to
administrators.  Possible future enhancements, depending on resources
and necessity, could include:
- A more streamlined interface for banning and unbanning apps, and for
  contacting app owners.
- A larger image, so that small nasty items can be seen more easily.
- Allowing editing or removal of certain additional fields.
- Better visual integration with the rest of the gallery.

**Comment by derrell** [comment]
in alpha023
