### ISSUE TITLE
Consider allowing HTML in project description

### ISSUE THREAD

**Issue by fgmart-zz** [app-inventor-gallery/aig#36]
Extending the project description to allow HTML would let users link to other content.  This could be valuable.

Related to #35.

**Comment by derrell** [comment]
This is dangerous, so if we implement it, we must be very careful. It would be possible to inject code, for example, such that when a user other than the owner of a project viewed the project, all of the viewing users' projects would get deleted. My inclination is to disallow HTML, but we may be able to filter the description so that only certain markup is allowed.

**Comment by fgmart-zz** [comment]
@wolberd

**Comment by cpuwhiz11** [comment]
Given the security issues involved and the limited user appeal I am closing this issue for now.
