### ISSUE TITLE
download count doesn't work

### ISSUE THREAD

**Issue by fgmart-zz** [app-inventor-gallery/aig#77]
title says it.

**Comment by derrell** [comment]
Any preference for whether to track Downloads as we do with Likes? I could simply increment the count, or I could create a new entity for each download, with a record of who has downloaded, and when. (With Likes, we need to do that so that we prevent the same person from adding to the Likes count multiple times. With downloads, that's not necessary, but it's easy enough to do if we want the additional info.)

**Comment by fgmart-zz** [comment]
I'd say just increment each time a download occurs.  Anonymous users should be able to download.  We will ultimately support non-logged in users?

**Comment by derrell** [comment]
Implemented in alpha020 (not yet default)
