### ISSUE TITLE
create and link Privacy Policy and Terms of Service page

### ISSUE THREAD

**Issue by fgmart-zz** [app-inventor-gallery/aig#86]
Create a page to display the privacy policy.
Insert text from Hal's approved copy.
Link to the privacy policy page next to TOS link at bottom of every page.

**Comment by derrell** [comment]
@mijoda to you

**Comment by derrell** [comment]
Contact me for the text to be presented for these.

**Comment by mijoda** [comment]
I have the footer with links to working local pages containing text copied from the docs.  Now I'm adding simple formatting.  Just to make sure:
- Hal's TOS replaces the Google one presently linked to, so we'll have 3 local pages and no links to Google.
- The TOS doc says "Terms of Use", not "Terms of Service", so I will call it that.

**Comment by fgmart-zz** [comment]
The new Terms of Use page will be one long scrolling page, right?

**Comment by mijoda** [comment]
Yes.  The 3 pages should be done today.

**Comment by derrell** [comment]
Exactly. Three new, local pages; no link to Google's page. Changing the link from "service" to "use" is fine.

**Comment by mijoda** [comment]
I issued a pull request for this and issue #91.  It took a little longer than I'd have liked due to my rustiness on HTML and CSS--thanks for the refresher course!

Let me know if you think there should be content or formatting changes.

I fixed a couple of obvious typos in the TOS:

You have the right to download delete them...    --> 
You have the right to download or delete them...

If you fee that others would find a project or comment mean...    --> 
If you feel that others would find a project or comment mean...

I may have missed some, so a careful reading may be in order, as unpleasant as that may be (although these are pretty friendly for legal documents).

Please also check that the small number of links point where they should, particularly the CC SA license.  Hal mentioned the possibility of putting in a logo for the license, but I punted on that.

I copied over the font-family list from the Gallery but pushed Trebuchet MS off the front since I don't like how it looks on legal docs, e.g. the M-as-upside-down-W in 'MIT'.  Feel free to put it back on, though.  I added some default sans-serif fonts for browsers that don't have Lucida Grande.

These need to be fixed before we go live:

privacy@INSERT.DOMAIN.HERE
Effective Date: March __, 2012

**Comment by derrell** [comment]
in 023.
