### ISSUE TITLE
Single-character description crashes app

### ISSUE THREAD

**Issue by derrell** [app-inventor-gallery/aig#98]
From @mijoda ...

I've been debugging some issues with setting status in my module
(about which more soon), and just encountered a related bug in myapps:
 If you enter a single-character app description, the app halts at
line 172 of MApps.js, in the _populateSearch() function, with a
"wordsToAdd is null" error.  Don't know why anyone would do that, but
it will happen.

**Comment by derrell** [comment]
Paul, to you.

**Comment by derrell** [comment]
Paul, I'm giving this one to Mike.

**Comment by mijoda** [comment]
Derrell, this one seems really simple.  Relevant code, from _populateSearch in MApps:

```
    // If it's one of the text fields...
    case "title":
    case "description":
      // Split up the words and...
      wordsToAdd = dataObj[appDataField].match(acceptable_word);
      wordsToAdd.forEach(function(word)
          {
            < do appropriate stuff... >
          });
      break;
```

The problem is that the code wants wordsToAdd to be the empty array when there are no matches, but in fact it's null, so null.forEach(...) throws an error.  So we move the wordsToAdd.forEach(...) loop into an if(wordsToAdd) {...} conditional and, done, world's shortest bugfix!

I'm assuming that we're OK with there being no matches.  I am.  Otherwise we have to build in additional prohibitions into the front end, which is needlessly complicated.  If some bored user w a n t s  t_o w.r.i.t.e. L`I'K`E t-h-i-s, who am I to stop him?  His app ends up being less searchable, maybe invisible to search, but that's hardly the end of the world.

Does this sound right?

**Comment by derrell** [comment]
That sounds right.

One common JavaScript way to make this change would be to change that one line as follows:

wordsToAdd = dataObj[appDataField].match(acceptable_word) || [ ];

**Comment by derrell** [comment]
Committed. Not yet online. Closing.
